//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.14 at 01:16:24 PM GMT+05:30 
//


package com.metacube.ipathshala.core.jaxb.value;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.metacube.ipathshala.core.jaxb.value package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Val_QNAME = new QName("", "val");
    private final static QName _Set_QNAME = new QName("", "set");
    private final static QName _OrderIndex_QNAME = new QName("", "order-index");
    private final static QName _ParentValue_QNAME = new QName("", "parent-value");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.metacube.ipathshala.core.jaxb.value
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ValueList }
     * 
     */
    public ValueList createValueList() {
        return new ValueList();
    }

    /**
     * Create an instance of {@link ValueElement }
     * 
     */
    public ValueElement createValueElement() {
        return new ValueElement();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "val")
    public JAXBElement<String> createVal(String value) {
        return new JAXBElement<String>(_Val_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "set")
    public JAXBElement<String> createSet(String value) {
        return new JAXBElement<String>(_Set_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "order-index")
    public JAXBElement<BigInteger> createOrderIndex(BigInteger value) {
        return new JAXBElement<BigInteger>(_OrderIndex_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "parent-value")
    public JAXBElement<String> createParentValue(String value) {
        return new JAXBElement<String>(_ParentValue_QNAME, String.class, null, value);
    }

}
