//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.14 at 01:16:23 PM GMT+05:30 
//


package com.netkiller.core.jaxb.set;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.metacube.ipathshala.core.jaxb.set package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SetOrder_QNAME = new QName("", "set-order");
    private final static QName _SetName_QNAME = new QName("", "set-name");
    private final static QName _ParentSetName_QNAME = new QName("", "parent-set-name");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.metacube.ipathshala.core.jaxb.set
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SetList }
     * 
     */
    public SetList createSetList() {
        return new SetList();
    }

    /**
     * Create an instance of {@link SetElement }
     * 
     */
    public SetElement createSetElement() {
        return new SetElement();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "set-order")
    public JAXBElement<String> createSetOrder(String value) {
        return new JAXBElement<String>(_SetOrder_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "set-name")
    public JAXBElement<String> createSetName(String value) {
        return new JAXBElement<String>(_SetName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "parent-set-name")
    public JAXBElement<String> createParentSetName(String value) {
        return new JAXBElement<String>(_ParentSetName_QNAME, String.class, null, value);
    }

}
